home/urls.py
from . import views
from .views import (
    HomeView, RegisterUser, LoginUser
)
from django.urls import include, path, re_path


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view()),
    # auth
    path('register/', RegisterUser.as_view(), name='register'),
    # verify
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('', include('home.urls')),
    path('words/', include('words.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    # social auth
    path('registration/', include('social_django.urls', namespace='social')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

words/urls.py
from django.urls import path

from words import views

app_name = 'words'
urlpatterns = [
    path('', views.WordListView.as_view(), name='all'),
    path('word/<int:pk>/', views.WordDetailView.as_view(), name='word_detail'),
    path('word/<int:pk>/favorite/', views.AddFavoriteView.as_view(), name='word_favorite'),
    path('word/<int:pk>/unfavorite/', views.DeleteFavoriteView.as_view(), name='word_unfavorite'),
    path('fav/', views.WordFavView.as_view(), name='word_fav'),
    path('word_translate/', views.WordTranslateView.as_view(), name='word_translate'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),

]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User


class UserPasswordResetForm(PasswordResetForm):
    pass


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль',  widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль',  widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

home/views.py
from django.shortcuts import render

# Create your views here.
from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth.views import (
    LoginView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib import messages
from django.views.generic.base import View
from .forms import RegisterUserForm, LoginUserForm
from django.urls import reverse_lazy
from owner import OwnwerCreateView
from django.shortcuts import render, redirect


class HomeView(View):
    template_name = 'home/main.html'

    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal,
            'settings': settings,
        }
        return render(request, self.template_name, context)


class RegisterUser(OwnwerCreateView):
    form_class = RegisterUserForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('/')

    def post(self, request):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(self.request, user, 'django.contrib.auth.backends.ModelBackend')
            messages.success(self.request, 'Регистрация Прошла успешно.')
            return redirect('words:all')
        else:
            messages.error(self.request, "Невалидная информация")
            form = RegisterUserForm()
            ctx = {'form': form}
            return render(request, self.template_name, ctx)


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'registration/login_social.html'


def logout_user(request):
    logout(request)
    return redirect('home:login')

home/templates/bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
    <link rel="stylesheet" href="{% static 'words/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'home/imgs/favicon.ico' %}"/>
{% block head %} {% endblock %}
    </head>
<body>
<!-- <div class="container"> -->
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
<div class="container">
{% block content %}
{% endblock %}
</div>
<!-- </div> -->
{% block footer %}
{% endblock %}
    <!--
    <home_scripts src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></home_scripts>
    -->
</body>
</html>

home/templates/menu.html
{% extends "bootstrap.html" %}
{% load app_tags %}
{% block navbar %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">Словарь Мюллера</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'words' as words %}
      <li {% if request.get_full_path == words %}class="active"{% endif %}>

          <a href="{% url 'words:all' %}">Поиск слов в словаре</a></li>
             <li {% if request.get_full_path == words %}class="active"{% endif %}>
          <a href="{% url 'words:word_fav' %}">Ваши любимые слова</a></li>
             <li {% if request.get_full_path == words %}class="active"{% endif %}>
          <a href="{% url 'words:word_translate' %}">Переводчик, который поддерживает 109 языков</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                    <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'home:logout' %}">Выйти</a></li>
                </ul>
            </li>
        {% else %}
            <li>
            <a href="{% url 'home:login' %}">Войти</a>
            </li>
            <li>
            <a href="{% url 'home:register' %}">Регистрация</a>
            </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
{% block content %}
User: {{ request.user }}

{% endblock %}