home/urls.py
from . import views
from .views import (
    HomeView, RegisterUser, LoginUser
)
from django.urls import include, path, re_path


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view()),
    # auth
    path('register/', RegisterUser.as_view(), name='register'),
    # verify
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('', include('home.urls')),
    path('words/', include('words.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    # social auth
    path('registration/', include('social_django.urls', namespace='social')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

words/urls.py
from django.urls import path

from words import views

app_name = 'words'
urlpatterns = [
    path('', views.WordListView.as_view(), name='all'),
    path('word/<int:pk>/', views.WordDetailView.as_view(), name='word_detail'),
    path('word/<int:pk>/favorite/', views.AddFavoriteView.as_view(), name='word_favorite'),
    path('word/<int:pk>/unfavorite/', views.DeleteFavoriteView.as_view(), name='word_unfavorite'),
    path('fav/', views.WordFavView.as_view(), name='word_fav'),
    path('word_translate/', views.WordTranslateView.as_view(), name='word_translate'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),

]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User


class UserPasswordResetForm(PasswordResetForm):
    pass


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль',  widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль',  widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

home/views.py
from django.shortcuts import render

# Create your views here.
from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth.views import (
    LoginView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib import messages
from django.views.generic.base import View
from .forms import RegisterUserForm, LoginUserForm
from django.urls import reverse_lazy
from owner import OwnwerCreateView
from django.shortcuts import render, redirect


class HomeView(View):
    template_name = 'home/main.html'

    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal,
            'settings': settings,
        }
        return render(request, self.template_name, context)


class RegisterUser(OwnwerCreateView):
    form_class = RegisterUserForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('/')

    def post(self, request):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(self.request, user, 'django.contrib.auth.backends.ModelBackend')
            messages.success(self.request, 'Регистрация Прошла успешно.')
            return redirect('words:all')
        else:
            messages.error(self.request, "Невалидная информация")
            form = RegisterUserForm()
            ctx = {'form': form}
            return render(request, self.template_name, ctx)


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'registration/login_social.html'


def logout_user(request):
    logout(request)
    return redirect('home:login')

home/templates/home/main.html
{% extends "menu.html" %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Добро пожаловать в приложение {{ settings.APP_NAME }}. Вы вошли как {{ request.user }}</h1>
    {% else %}
        <h2>Вы не зарегистрированы</h2>
    {% endif %}
    <p>
    На сайте вы можете посмотреть слова из словаря Мюллера, прослушать озвучку, увидеть перевод, фразы, грамматику и многое другое.
    </p>
<p>Также вы можете добавить любимые слова в ваш личный словарь, для этого выберите слово нажав на звёздочку</p>
<p>Если вы хотите перевести Фразы и даже несколько предложений, используйте переводчик Translator, который поддерживает 109 языков</p>
<p>При возникновении ошибок, отправьте по почте сообщения, дайте мне знать что можно было бы исправить</p>
<p>В словаре 526 876 слов и словосочетаний</p>
<p>Словарь весит 107 MB</p>
<a href="{% url 'words:contact' %}">Форма обратной связи</a> Или пишите на почту - artem.ismagilov.2000@mail.ru :)
<hr>
<p><i>,,Учитесь и читайте. Читайте книги серьезные. Жизнь сделает остальное.''   </i>Достоевский Ф. М.</p>
<div>
    <img src="{%  static 'home/imgs/background.jpg' %}" style="width: 80%;">

</div>
{% endblock content %}