home/urls.py
from . import views
from .views import (
    HomeView, RegisterUser, LoginUser
)
from django.urls import include, path, re_path


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view()),
    # auth
    path('register/', RegisterUser.as_view(), name='register'),
    # verify
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('', include('home.urls')),
    path('words/', include('words.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    # social auth
    path('registration/', include('social_django.urls', namespace='social')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

words/urls.py
from django.urls import path

from words import views

app_name = 'words'
urlpatterns = [
    path('', views.WordListView.as_view(), name='all'),
    path('word/<int:pk>/', views.WordDetailView.as_view(), name='word_detail'),
    path('word/<int:pk>/favorite/', views.AddFavoriteView.as_view(), name='word_favorite'),
    path('word/<int:pk>/unfavorite/', views.DeleteFavoriteView.as_view(), name='word_unfavorite'),
    path('fav/', views.WordFavView.as_view(), name='word_fav'),
    path('word_translate/', views.WordTranslateView.as_view(), name='word_translate'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),

]

words/models.py
from django.db import models

# Create your models here.
from django.conf import settings


class Word(models.Model):
    eng = models.CharField(max_length=200)
    tr = models.TextField(null=True)
    rus = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='word_owner', null=True)
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Fav', related_name='favorite_words')

    def __str__(self):
        return self.eng


class Fav(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('word', 'user')

words/views.py
# Create your views here.
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, FormView
from .models import Fav, Word
from owner import *
from .forms import *
from .words_scripts.lingvo import get_data, parse_json
from .words_scripts.translate import run_translate
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'words/contact.html'
    success_url = reverse_lazy('words:all')

    def form_valid(self, form):
        return redirect('words:all')


class WordListView(OwnerListView):
    model = Word
    template_name = 'words/word_list.html'

    def get(self, request, *args, **kwargs):
        word_list = Word.objects.all()
        favorites = []

        paginator = Paginator(word_list, 50)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        if request.user.is_authenticated:
            rows = request.user.favorite_words.values('id')
            favorites = [row['id'] for row in rows]

        form = ListForm()
        ctx = {
            'form': form,
            "page_obj": page_obj,
            'favorites': favorites
        }
        return render(request, self.template_name, ctx)

    def post(self, request):
        word_list = list()
        favorites = list()
        form = ListForm(request.POST)
        if form.is_valid() and request.POST:
            data = form.cleaned_data
            count = data.get('count')
            strval = data.get('search')
            exact = data.get('exact')
            if request.user.is_authenticated:
                rows = request.user.favorite_words.values('id')
                favorites = [row['id'] for row in rows]
            filter_arg = {'eng__startswith': strval} if not exact else {'eng__exact': strval}
            if strval and count.isdigit():
                word_list = Word.objects.filter(**filter_arg)[:int(count)]
            elif strval:
                word_list = Word.objects.filter(**filter_arg)
            ctx = {
                'word_list': word_list,
                'favorites': favorites,
                'search': strval, 'form': form
            }
            return render(request, self.template_name, ctx)


class WordTranslateView(OwnerDetailView):
    template_name = 'words/word_translate.html'
    success_url = reverse_lazy('words:word_translate')

    def get(self, request, *args, **kwargs):
        form = TranslateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        translate_word = run_translate(
            request.POST['from_translate'], request.POST['from_lang'], request.POST['to_lang']
        )
        form = TranslateForm(request.POST, initial={"to_translate": translate_word})
        if form.is_valid():
            ctx = {'form': form, 'translate_word': translate_word}
            return render(request, self.template_name, ctx)


class WordDetailView(OwnerDetailView):
    model = Word
    template_name = 'words/word_detail.html'

    def get(self, request, pk, *args, **kwargs):
        word = Word.objects.get(id=pk)
        ctx = {'word': word}
        try:
            data = parse_json(get_data(word=word.eng))
        except TypeError as type_er:
            print(type_er)
            data = {}
        ctx.update(data)
        return render(request, self.template_name, ctx)


class WordFavView(OwnerListView):
    model = Word
    template_name = 'words/word_fav.html'

    def get(self, request, *args, **kwargs):
        favorites = []
        if request.user.is_authenticated:
            rows = request.user.favorite_words.values('id')
            favorites = [r['id'] for r in rows]
        word_list = [Word.objects.get(pk=pk) for pk in favorites]
        ctx = {'word_list': word_list, 'favorites': favorites}
        return render(request, self.template_name, ctx)


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        print("Add PK", pk)
        word = get_object_or_404(Word, id=pk)
        fav = Fav(user=request.user, word=word)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        print("Delete PK", pk)
        word = get_object_or_404(Word, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, word=word).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

words/templates/words/contact.html
{% extends "menu.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Отправить</button>
</form>
{% endblock%}

words/templates/words/word_detail.html
{% extends "menu.html" %}
{% block content %}
{% load static %}
<div class="head">
<h1>{{ word.eng }}</h1>
{% if sound %}
<img onclick="play('{{ sound_file }}')" src="{%  static 'words/imgs/sound.png' %}" style="width: 30px;">
{% endif %}
{% if word.tr %}
<i>брит. </i><strong><i>{{ word.tr }}</i></strong>
{% endif %}
</div>

<img class='word' src="{{ word_img }}">

{% if word.rus %}
    <p>{{ word.rus|linebreaks }}</p>
{% endif %}
<hr/>
<ol>
    {% for i in phrases %}
    <li><strong>{{ i.0 }}</strong> - {{ i.1 }}</li>
{% endfor %}

</ol>


{% for fs in forms_words %}
    {% if fs %}
        {% for f in fs %}
            {% if f and fs.0 == f %}
                <div class="column first_col">{{ f }}</div>
            {% elif f %}
                <div class="column">{{ f }}</div>
            {% endif %}
        {% endfor %}
    <br>
    {% endif %}
{% endfor %}
<script type="text/javascript">
function play(byte) {
    console.log(byte);
    var audio = new Audio("data:audio/wav;base64,"+byte);
    audio.play();
}
</script>
{% endblock %}

words/templates/words/word_fav.html
{% extends "menu.html" %}
{% block content %}
<script>
    function favPost(url, word_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+word_id).toggle();
        $("#favorite_star_"+word_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
<h1>Личный словарь</h1>
{% if word_list %}
    <ul>
    {% for word in word_list %}
        <li>
            {% if user.is_authenticated %}

                <a href="{% url 'words:word_detail' word.id %}"><strong>{{ word.eng }}</strong>
                    <a href="#" onclick=
                     "favPost('{% url 'words:word_favorite' word.id %}', {{ word.id }} );return false;"
                    {% if word.id in favorites %} style="display: none;" {% endif %} id="unfavorite_star_{{ word.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>

                <a href="#" onclick="favPost('{% url 'words:word_unfavorite' word.id %}', {{ word.id }} );return false;"
                    {% if word.id not in favorites %} style="display: none;" {% endif %} id="favorite_star_{{ word.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>

            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Your dictionary is empty</p>
{% endif %}

{% endblock %}

words/templates/words/word_list.html
{% extends "menu.html" %}
{% load crispy_forms_tags %}

{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'words/css/style.css' %}">

<script>
function favPost(url, word_id) {
console.log('Requesting JSON');
$.post(url, {},  function(rowz){
    console.log(url, 'finished');
    $("#unfavorite_star_"+word_id).toggle();
    $("#favorite_star_"+word_id).toggle();
}).fail(function(xhr) {
    alert('Url failed with '+xhr.status+' '+url);
});
}
</script>

<div>
<form action="" method="post" style="float:right;">
    {% csrf_token %}
    {{ form }}
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'words:all' %}"><i class="fa fa-undo"></i></a>
</div>

{% if word_list %}
    <div>
    {% for word in word_list %}
        <a href="{% url 'words:word_detail' word.id %}">

                <div id="my_div" class="row"><strong>{{ word.eng }}</strong>
            {% if user.is_authenticated %}
                <a href="#" onclick="favPost('{% url 'words:word_unfavorite' word.id %}', {{ word.id }} );return false;"
                    {% if word.id not in favorites %} style="display: none;" {% endif %} id="favorite_star_{{ word.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>
                <a href="#" onclick=
                     "favPost('{% url 'words:word_favorite' word.id %}', {{ word.id }} );return false;"
                    {% if word.id in favorites %} style="display: none;" {% endif %} id="unfavorite_star_{{ word.id }}">
                <span class="fa-stack" style="vertical-align: middle;">
                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                <i class="fa fa-star-o fa-stack-1x"></i>
                </span>
                </a>
            {% endif %}
        </div></a>

    {% endfor %}
</div>
{% else %}
    <p>No words are available.</p>


    {% for word in page_obj %}
<div>
    <a href="{% url 'words:word_detail' word.id %}">

        <div id="my_div" class="row"><strong>{{ word.eng }}</strong>
    {% if user.is_authenticated %}
        <a href="#" onclick="favPost('{% url 'words:word_unfavorite' word.id %}', {{ word.id }} );return false;"
            {% if word.id not in favorites %} style="display: none;" {% endif %} id="favorite_star_{{ word.id }}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <a href="#" onclick=
             "favPost('{% url 'words:word_favorite' word.id %}', {{ word.id }} );return false;"
            {% if word.id in favorites %} style="display: none;" {% endif %} id="unfavorite_star_{{ word.id }}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>

            {% endif %}
        </div></a>
</div>

    {% endfor %}


            <div class="pagination" style="font-size: 30px;">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    {% if page_obj.number %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
{% endif %}

{% endblock %}

words/templates/words/word_translate.html
{% extends "menu.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<h1>Translator</h1>
<p>
  <form method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.from_lang|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.to_lang|as_crispy_field }}
      </div>
  </div>
  <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.from_translate|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.to_translate|as_crispy_field }}
      </div>
  </div>
  <div>
    <input type="submit" value="Translate" class="btn btn-primary">
    <input type="submit" value="Cancel" class="btn btn-danger" onclick="window.location.href='{% url 'words:all' %}';return false;">
  </div>

  </form>
</p>
{% for t in tt %}
  <p><strong>t</strong></p>
{% endfor %}

<h2>{{ tt }}</h2>
<h1><i>{{ to_tr }}</i>{{ from_tr }}</h1>
<div>
{% for w in tt %}
  <b>{{ w }}, </b>
  {% endfor %}
</div>
<i>{{ en_tr }}</i>
<i>{{ ru_tr }}</i>
<div>
{% for w in v %}
  <p>{{ w }}, </p>
    {% endfor %}
</div>
<div>
{% for w in a %}
  <p>{{ w }}, </p>
    {% endfor %}
</div>
<div>
{% for w in n %}
  <p>{{ w }}, </p>
    {% endfor %}
</div>
{% endblock %}